# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Django" = super.buildPythonPackage rec {
    pname = "Django";
    version = "2.2.24";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/4a/3d3f05ff8cb284cca565adb8b704b3094b0810ae2b5925c6e30e604400f7/Django-2.2.24-py3-none-any.whl";
      sha256 = "14jzx6sz0fx7c48g3kggy494xbsx8dyi1m1c3iiiwszqrzp4q27j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
      self."sqlparse"
    ];
  };
  "Pillow" = super.python.pkgs.pillow;
  #"Pillow" = super.buildPythonPackage rec {
  #  pname = "Pillow";
  #  version = "8.3.1";
  #  src = fetchurl {
  #    url = "https://files.pythonhosted.org/packages/8f/7d/1e9c2d8989c209edfd10f878da1af956059a1caab498e5bc34fa11b83f71/Pillow-8.3.1.tar.gz";
  #    sha256 = "14n7wawxq6im3m8qdk6c0c9ixriybr6hhzxyzplfqp7wkf1m7b1c";
  #  };
  #  format = "setuptools";
  #  doCheck = false;
  #  buildInputs = with pkgs; [ freetype libjpeg openjpeg libimagequant zlib libtiff libwebp tcl lcms2 ];
  #  checkInputs = [];
  #  nativeBuildInputs = [];
  #  propagatedBuildInputs = [];
  #};
  "PyJWT" = super.buildPythonPackage rec {
    pname = "PyJWT";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/32/d5d3cab27fee7f6b22d7cd7507547ae45d52e26030fa77d1f83d0526c6e5/PyJWT-2.1.0-py3-none-any.whl";
      sha256 = "18gwfgqh6cpd2xsc3qjf729aicln1vsszlap70ylic4ipbxp6kck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/fd/15638de2da0a5aa91c095718444624aa565f766fc178249ca6faa372f71a/PyYAML-5.4.tar.gz";
      sha256 = "12n1i895zma9fzq6g2kncarqkniwnm6vnqvdazyn9z9lq2df6j9w";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "amqp" = super.buildPythonPackage rec {
    pname = "amqp";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/90/bb5ce93521772f083cb2d7a413bb82eda5afc62b4192adb7ea4c7b4858b9/amqp-2.6.1-py2.py3-none-any.whl";
      sha256 = "0ndaq0j3901p6ihdc8jq2fwc1nh4ga82j4jc8waizjc7p0zk2zxa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."vine"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "21.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl";
      sha256 = "1cdh2v3scv9mi00195khsch3y6l8wvq0rmjsjmxdn85cv3b917hl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "beautifulsoup4" = super.buildPythonPackage rec {
    pname = "beautifulsoup4";
    version = "4.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl";
      sha256 = "0n0q7625j1jrjw70l822z743l476h5argaz15a9lx6slrgv40iq3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."soupsieve"
    ];
  };
  "billiard" = super.buildPythonPackage rec {
    pname = "billiard";
    version = "3.6.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/5e/7591866ff45b370354bd20291cb6f87ddb2eef1f1c88c890a38412037e11/billiard-3.6.3.0-py3-none-any.whl";
      sha256 = "1pjyvw66lll04bnvfnsnqc3vq2svf6dpv1zrqbxy19jr112pbxdz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "boto3" = super.buildPythonPackage rec {
    pname = "boto3";
    version = "1.13.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/a9/1e321ad1a91355f91af9261e176c6aabf543019317a0e8c59dd2fd981c18/boto3-1.13.16-py2.py3-none-any.whl";
      sha256 = "1sx2c2gxikfpwr6fcq3gyz1bngc20r2r9k04kzbw0yvvsjq6f3b5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."botocore"
      self."jmespath"
      self."s3transfer"
    ];
  };
  "botocore" = super.buildPythonPackage rec {
    pname = "botocore";
    version = "1.16.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/ac/b21f4aba98f239ee5341d79c64bb502a64ad8ac98331bf0d9568707c6576/botocore-1.16.16-py2.py3-none-any.whl";
      sha256 = "17j55fxgp2sffb7jiikwawayg7nhgm1krwp54yf3y3iz08yh4x82";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."jmespath"
      self."python-dateutil"
      self."urllib3"
    ];
  };
  "cachetools" = super.buildPythonPackage rec {
    pname = "cachetools";
    version = "4.2.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ea/c1/4740af52db75e6dbdd57fc7e9478439815bbac549c1c05881be27d19a17d/cachetools-4.2.4-py3-none-any.whl";
      sha256 = "1lgji50pgcbigi9k0xd316rmz3qsy9bidfy7yzzpxafjnwy1v5wj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "celery" = super.buildPythonPackage rec {
    pname = "celery";
    version = "4.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/0c/609e3611d20c9f8d883852d1be5516671f630fb08c8c1e56911567dfba7b/celery-4.4.7-py2.py3-none-any.whl";
      sha256 = "0ifa7f4p46kx47asr7hrr0vx0dk2s6bkjah38yviyy2hwrb1sbm9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."billiard"
      self."kombu"
      self."pytz"
      self."vine"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2021.10.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl";
      sha256 = "0scm6gbbk4gfwb1flivxihnim9wragvvvcia0jn488scxdih2ann";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.14.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/20/025f59f929bbcaa579704f443a438135918484fffaacfaddba776b374563/cffi-1.14.5.tar.gz";
      sha256 = "174d6814x3qca0kn5qwq4l1ab8aabc0rmnvfxwr9yw4iwpzfay7x";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = with pkgs; [ libffi ];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "4.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl";
      sha256 = "198xs99vbvcj312d1bk7bgn7aix5h64sqi3hwvr1i4gxcr6har7q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "7.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl";
      sha256 = "1p607168jqq20d8bngrkfqv0vvkfas57r6s8szimvpgs9fgsik6s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "confluent-kafka" = super.buildPythonPackage rec {
    pname = "confluent-kafka";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/7f/bb959d5be7d59e758557dea6c2e6f7f8ac3c347953f95af160abc6bad0f3/confluent-kafka-1.6.0.tar.gz";
      sha256 = "0g76zvn6xiazzab5wifyfj3mz8gilfdnh3ziqxjwv1rfn2ysm74a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = with pkgs; [ rdkafka self."requests" ];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "croniter" = super.buildPythonPackage rec {
    pname = "croniter";
    version = "0.3.37";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/e5/1d2b7e3c36c444e78a31d7f0b8a1799acf4f8d869693f2232a3555a5dc6f/croniter-0.3.37-py2.py3-none-any.whl";
      sha256 = "16yp4rsfbzh4pv6mj9nj5n66j0kwqlsk869nqc49wdx9kj43lmwg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."natsort"
      self."python-dateutil"
    ];
  };
  cryptography = super.python.pkgs.cryptography;
  #"cryptography" = super.buildPythonPackage rec {
  #  pname = "cryptography";
  #  version = "3.4.8";
  #  src = fetchurl {
  #    url = "https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz";
  #    sha256 = "072awar70cwfd2hnx0pvp1dkc7gw45mbm3wcyddvxz5frva5xk4l";
  #  };
  #  format = "setuptools";
  #  doCheck = false;
  #  buildInputs = [];
  #  checkInputs = [];
  #  nativeBuildInputs = [];
  #  propagatedBuildInputs = [
  #    self."cffi"
  #  ];
  #};
  "cssselect" = super.buildPythonPackage rec {
    pname = "cssselect";
    version = "1.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/44/25b7283e50585f0b4156960691d951b05d061abf4a714078393e51929b30/cssselect-1.0.3-py2.py3-none-any.whl";
      sha256 = "01kjxwbjrdafxl2plcwspfw0cbbkvxq3p6cdlqvfkacxg3l06l9v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cssutils" = super.buildPythonPackage rec {
    pname = "cssutils";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6b/15/a9fb9010f58d1c55dd0b7779db2334feb9a572d407024f39a60f44293861/cssutils-1.0.2-py3-none-any.whl";
      sha256 = "13aw2bppz3lq4w8fvwah680xsj1m4qv53cdd9rvm4l1gr4cvwkf7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "dataclasses" = super.buildPythonPackage rec {
    pname = "dataclasses";
    version = "0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/2f/1095cdc2868052dd1e64520f7c0d5c8c550ad297e944e641dbf1ffbb9a5d/dataclasses-0.6-py3-none-any.whl";
      sha256 = "17ywa7lh906h4ad04gzmwgsj4y2pg6z5kqkizm7a9zf7i3bnjjj5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "datadog" = super.buildPythonPackage rec {
    pname = "datadog";
    version = "0.29.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/82/110a3978f07cfc58a4b4c1edac934d493ec2f174e0d18d23afed9c0829c9/datadog-0.29.3-py2.py3-none-any.whl";
      sha256 = "02ksiqzna5na79ln4h5z86sqmd8zyq9dzk4s6l0q42zgv5xp4cqf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."requests"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/cc/d7b758e54779f7e465179427de7e78c601d3330d6c411ea7ba9ae2f38102/decorator-5.1.0-py3-none-any.whl";
      sha256 = "0x5khfkd8gqhjisi6jr6nyddw0yb4a8mwcspw4lkl85bqv1yf4kv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl";
      sha256 = "14zglgld9yp35l89dqs9ayfdsix84yrs3dqvb2mp90s3f03ib1v6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "django-crispy-forms" = super.buildPythonPackage rec {
    pname = "django-crispy-forms";
    version = "1.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/27/9d6eef25ee96060b20a8df3cc6f6e5f98492900fada0b736767daf6f8f1c/django_crispy_forms-1.8.1-py2.py3-none-any.whl";
      sha256 = "123y86y7kmpyd9q3namjq6brz0g36qvcqab8q51fzygn67713drd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "django-picklefield" = super.buildPythonPackage rec {
    pname = "django-picklefield";
    version = "2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/f7/0b6002027ef42490ac439680dfeaf212a12d40f2bbe70e65fa0768f2c700/django_picklefield-2.1-py2.py3-none-any.whl";
      sha256 = "1xrswkjw73m2q6sriv7rncnq5bwki1s34nq91rz94411dnh0ivxh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Django"
    ];
  };
  "djangorestframework" = super.buildPythonPackage rec {
    pname = "djangorestframework";
    version = "3.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/7c/4cfacd5a93eab48c1714da0422d88b031dfb94f6795c2d5ef9a348f1f376/djangorestframework-3.11.2-py3-none-any.whl";
      sha256 = "12d7kspx33qq5nwx2s3lj6y1ynwrw43r29ipg14n6r079gf29isw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Django"
    ];
  };
  "docutils" = super.buildPythonPackage rec {
    pname = "docutils";
    version = "0.15.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl";
      sha256 = "1l5nk52lmds6gjak2az9b7q43g8fhiilnn8cpaw1z7xpcdj6jkvc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "email-reply-parser" = super.buildPythonPackage rec {
    pname = "email-reply-parser";
    version = "0.5.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/8d/11696d31eafc68ceea8108f635d30aefc6df9cb27640949f45aec963d637/email_reply_parser-0.5.12-py3-none-any.whl";
      sha256 = "1zc5lqghqnn8z9ds7q6fbjmzjqiwwkwhx8warw5057k7hhic169l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "google-api-core" = super.buildPythonPackage rec {
    pname = "google-api-core";
    version = "1.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/fb/2ec182926a23b2e13d07680ba667599939059abf62a16fa2689d22de47f8/google_api_core-1.25.1-py2.py3-none-any.whl";
      sha256 = "1fwg9ai9l1l442cgr8w6v098l9xj4swcr4vh9g99h41qxlvdcb99";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."googleapis-common-protos"
      self."protobuf"
      self."pytz"
      self."requests"
      self."setuptools"
      self."six"
    ];
  };
  "google-auth" = super.buildPythonPackage rec {
    pname = "google-auth";
    version = "1.24.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/fd/df1b3a59aca9537a187413651ad63b290d165559150a868a298fa837fe7b/google_auth-1.24.0-py2.py3-none-any.whl";
      sha256 = "1f5c8skbvr5yhdriq0hv4qh4nl879gpkb14jz7dpkx1i3k2jqxff";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cachetools"
      self."pyasn1-modules"
      self."rsa"
      self."setuptools"
      self."six"
    ];
  };
  "google-cloud-bigtable" = super.buildPythonPackage rec {
    pname = "google-cloud-bigtable";
    version = "1.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/78/0dd9ea16e3bf135f2d87a51482330f2ae5ca417c3b7ce66f811f25baa8ec/google_cloud_bigtable-1.6.1-py2.py3-none-any.whl";
      sha256 = "0c15dfkxqqsrvv6yzivm46nrh66rldhsp8j3jvk4lbdv0dnfs1c6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-api-core"
      self."google-cloud-core"
      self."grpc-google-iam-v1"
    ];
  };
  "google-cloud-core" = super.buildPythonPackage rec {
    pname = "google-cloud-core";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/82/d54bdbdbae02c66ec26c97eb684cfb27af82b3e286497625b815c4741792/google_cloud_core-1.5.0-py2.py3-none-any.whl";
      sha256 = "1xbr1209s0aiav3l1gwapbdzpkd9abwla7ys3fqz4lvg81gs3a4r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-api-core"
      self."six"
    ];
  };
  "google-cloud-pubsub" = super.buildPythonPackage rec {
    pname = "google-cloud-pubsub";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/a1/76f3df731f8405e118bd1c91f8091351062ee742807ccac52afaa1e0825b/google_cloud_pubsub-2.2.0-py2.py3-none-any.whl";
      sha256 = "0ibfq3dzvj6h7l8hrxg0li0mmd9x990qjmwvx3z1lr1sc3rl7sj4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-api-core"
      self."grpc-google-iam-v1"
      self."libcst"
      self."proto-plus"
    ];
  };
  "google-cloud-storage" = super.buildPythonPackage rec {
    pname = "google-cloud-storage";
    version = "1.35.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/6e/b5b745dc1eb31d1ce50df25200b9f74ef36f57f9d226018bcb48e664c728/google_cloud_storage-1.35.0-py2.py3-none-any.whl";
      sha256 = "0pbcig6px3ganxfslqy70j72130nmdhhhysw67dcbznshd3bfj3v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."google-cloud-core"
      self."google-resumable-media"
      self."requests"
    ];
  };
  "google-crc32c" = super.buildPythonPackage rec {
    pname = "google-crc32c";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/de/477cdcfd3ba2877cdf798f0328ea6aa79b2e632d169f5099d6240c4c4ebf/google-crc32c-1.3.0.tar.gz";
      sha256 = "1ps4qaccij6cixs91772y9f9r1n702yfzy4qqmds6x5h7qkycv97";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "google-resumable-media" = super.buildPythonPackage rec {
    pname = "google-resumable-media";
    version = "1.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/2b/e342559b2e7c125c06b33f6a8028afaf35378202b6764b41894ab5fb48f5/google_resumable_media-1.3.3-py2.py3-none-any.whl";
      sha256 = "1fplblaq0gn9pqmb47haccpcfg7l560z1v94k504wynn7hakjbq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-crc32c"
      self."six"
    ];
  };
  "googleapis-common-protos" = super.buildPythonPackage rec {
    pname = "googleapis-common-protos";
    version = "1.52.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/74/3956721ea1eb4bcf7502a311fdaa60b85bd751de4e57d1943afe9b334141/googleapis_common_protos-1.52.0-py2.py3-none-any.whl";
      sha256 = "091y82cgcwkqhmnhszij76d4xk700ghmnrvvsc8sgndaymh1g5n8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "grpc-google-iam-v1" = super.buildPythonPackage rec {
    pname = "grpc-google-iam-v1";
    version = "0.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/19/2060c8faa325fddc09aa67af98ffcb6813f39a0ad805679fa64815362b3a/grpc-google-iam-v1-0.12.3.tar.gz";
      sha256 = "0wmab3lkyf1k4ggg5l0b6066wjwknh6xzh4i3815gx28yrb5pyqb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."googleapis-common-protos"
      self."grpcio"
    ];
  };
  "grpcio" = super.buildPythonPackage rec {
    pname = "grpcio";
    version = "1.40.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/56/700ff83b59eb69a7ddd62840666699173923020cfdf33a2860b9eba5667a/grpcio-1.40.0.tar.gz";
      sha256 = "0fpyrr0q9jhhr0pblsp31zz6bd1avv11fvhvvc22csl8zrc225rx";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "hiredis" = super.buildPythonPackage rec {
    pname = "hiredis";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/7e/45eeca7614f469e7ca924c751457e53274de0eecc3bbff2d2aa19d1ca4ea/hiredis-0.3.1.tar.gz";
      sha256 = "1q6c3nyjbz7ci4y53i5h10kbill8irdddcl3kaqxcak1ilcnbxbv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl";
      sha256 = "1h280sli58v5dapmf79rnnqdrrk0xjn8vi3pxppknllv3r5q0zdr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "isodate" = super.buildPythonPackage rec {
    pname = "isodate";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl";
      sha256 = "109cfyn25wyn4ac0h4nc6xrv9cwazldbir4nr8m3bxa0cv036kda";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "jmespath" = super.buildPythonPackage rec {
    pname = "jmespath";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl";
      sha256 = "0bxp1hnjrb4vaksa43s2ghjwr3jb5rpv6q8x2hq7fnfc0icm5xnd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl";
      sha256 = "0qyidiicwn27ya7r4q7cjbra8gna5vkwnfg1kkp7nmvg47w3qnsf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
  };
  "kombu" = super.buildPythonPackage rec {
    pname = "kombu";
    version = "4.6.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/34/3eea6a3a9ff81b0c7ddbdceb22a1ffc1b5907d863f27ca19a68777d2211d/kombu-4.6.11-py2.py3-none-any.whl";
      sha256 = "02hfbcjj9vlhb6gzx2fihdj4h24lyrrkslyn7bcr88aanpzwsj5y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
    ];
  };
  "libcst" = super.buildPythonPackage rec {
    pname = "libcst";
    version = "0.3.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/b8/788385690cf5f2189f4539545b90ff72cce52919a30b313149c521094e46/libcst-0.3.21-py3-none-any.whl";
      sha256 = "07is5nrl8ic4cg3k9ab3z6magalrq3g50s0cwj3jzy9vzajgxim9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYAML"
      self."typing-extensions"
      self."typing-inspect"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz";
      sha256 = "0s14r1w2x9sdlcsw8mxiqgw4rz5zs5lpqpxrfyn4a1mkndqqbdrr";
    };
    format = "setuptools";
    doCheck = false;
    nativeBuildInputs = with pkgs; [ libxml2.dev libxslt.dev ];
    buildInputs = with pkgs; [ libxml2 libxslt zlib ];
    checkInputs = [];
    propagatedBuildInputs = [];
  };
  "maxminddb" = super.buildPythonPackage rec {
    pname = "maxminddb";
    version = "2.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/90/e1718dc14b9ecc7e1ef627f577d92d644a4acebcb4d97f6a6918e12591ba/maxminddb-2.0.3.tar.gz";
      sha256 = "1p678y3pj25n2nwg89asvv4lp9vq6ax39slrik4gl56q9l46ms27";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "milksnake" = super.buildPythonPackage rec {
    pname = "milksnake";
    version = "0.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/be/e10e73f857ac98ef43587fa8db37a3ef6de56e728037a7b9728de26711c7/milksnake-0.1.5-py2.py3-none-any.whl";
      sha256 = "1d7nasi4zf8sf2bjlfh2xp030xilp1mkx4ssxr4l2wi28bya232m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "mistune" = super.buildPythonPackage rec {
    pname = "mistune";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl";
      sha256 = "1m5qdckapi46npn36jqljlj2dqgzdm3qslz8xs4a5381fcc0b8c8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mmh3" = super.buildPythonPackage rec {
    pname = "mmh3";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/54/78c7f04ceee4913cbe7b33e253867c1da2291c80dfa6062dc6aaabb6cef8/mmh3-3.0.0.tar.gz";
      sha256 = "1ia1bjm1xrfcdwb3rrsx8nipyfa6fnw41rcvxhc3azd01665gv6i";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mock" = super.buildPythonPackage rec {
    pname = "mock";
    version = "4.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/03/b7e605db4a57c0f6fba744b11ef3ddf4ddebcada35022927a2b5fc623fdf/mock-4.0.3-py3-none-any.whl";
      sha256 = "0qpf9q22bvib5v2fg2rxmwd07mvm33asgms87xdsvkrpxrjcnbqj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "msgpack" = super.buildPythonPackage rec {
    pname = "msgpack";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/4f/057549afbd12fdd5d9aae9df19a6773a3d91988afe7be45b277e8cee2f4d/msgpack-1.0.0.tar.gz";
      sha256 = "1h5mxh84rcw04dvxy1qbfn2hisavfqgilh9k09rgyjhd936dad4m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mypy-extensions" = super.buildPythonPackage rec {
    pname = "mypy-extensions";
    version = "0.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl";
      sha256 = "0pgi8sl514i9iamzdli8l3sxla7l4ic3nc713klrm9j5b7bys3q9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "natsort" = super.buildPythonPackage rec {
    pname = "natsort";
    version = "7.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/23/8b6acd2e9c0b427802dd45aacf0b2a0250893c3b26c7b1340589a588cc2a/natsort-7.1.1-py3-none-any.whl";
      sha256 = "0zmn8n84i3n0vsc0z4n7vkp6azy627qrp3b3xyjs8gqnr83grx6h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "oauthlib" = super.buildPythonPackage rec {
    pname = "oauthlib";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/5d/9dd1c29e5a786525f6342f6c1d812ed2e37edc653ad297048c1668988053/oauthlib-3.1.1-py2.py3-none-any.whl";
      sha256 = "1k1hfyfkyq46m2ih51p1jxrdk4w1z3kgqwfrak5nm37dq9a67gs2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl";
      sha256 = "057z2kyp5f66w7gz9ph0h3d4f20gfvgblsadr4ff6m8d4bwm8qn8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "parsimonious" = super.buildPythonPackage rec {
    pname = "parsimonious";
    version = "0.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/89/32c55944cd30dff856f16859ee325b13c83c260d0c56c0eed511e8063c87/parsimonious-0.8.0.tar.gz";
      sha256 = "0sq81p00vsilvwyqpzp66vwbygp791bmyfii4hzp0mvf5bbnj25f";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "petname" = super.buildPythonPackage rec {
    pname = "petname";
    version = "2.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8e/a5/348c90b3fb09d7bd76f7dacf1b92e251d75bfbe715006cb9b84eb23be1b1/petname-2.6.tar.gz";
      sha256 = "0k4y9jrxb68wgb37hid1xmch2bhhgk3bf6qdcirs6mi3fzpk274q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "phabricator" = super.buildPythonPackage rec {
    pname = "phabricator";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/98/f8ab84ec69776bea7e2346f86e3c033e92a40f8d565b9b16021d1737443f/phabricator-0.7.0.tar.gz";
      sha256 = "0axvx7h469zz46ny8v211i217hhvqigzzc20kl0riy42cvzif13v";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "phonenumberslite" = super.buildPythonPackage rec {
    pname = "phonenumberslite";
    version = "8.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/b1/bca369f70e81df31496be62c674deaebbfa9eebfe815e07588d929955704/phonenumberslite-8.12.0-py2.py3-none-any.whl";
      sha256 = "1x8gr8wg1mxwgmszpqav14iqkd246pws3m2qi9v448w1njf7iifn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "progressbar2" = super.buildPythonPackage rec {
    pname = "progressbar2";
    version = "3.32.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/fd/7b6facd44205a94538f379731e269983d1bf401de888d16ab66c043abfaf/progressbar2-3.32.0-py2.py3-none-any.whl";
      sha256 = "085ayshr73dqsaglf8zj64rdcgyl17ghwxnjc58jafi16n6v3fkq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-utils"
    ];
  };
  "proto-plus" = super.buildPythonPackage rec {
    pname = "proto-plus";
    version = "1.19.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/72/01301bc3006487116e65a7ae581487942676a7f779dff5b5db10a0c560ac/proto_plus-1.19.4-py3-none-any.whl";
      sha256 = "0whh0bhkn71in990l23abb6lcrj0l3hh5973698sz50yhvzys5q2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "3.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/3e/19b09fd98ca30a9cd53269806602ffe1d32464fe1f662ec8765a215f0495/protobuf-3.18.1.tar.gz";
      sha256 = "07iri786d3n4zxpcf1brjwl8dmlr13ly4b6i1lq8f43m0c2v96qw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "psycopg2-binary" = super.buildPythonPackage rec {
    pname = "psycopg2-binary";
    version = "2.8.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/51/0f2c6aec5c59e5640f507b59567f63b9d73a9317898810b4db311da32dfc/psycopg2-binary-2.8.6.tar.gz";
      sha256 = "180s1shfbqjrfsf1assrlvrch8df4jw7j8s2kq980w89rvmw1f8i";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ pkgs.postgresql ];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.4.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl";
      sha256 = "0pda8szs8jsaknf4ggilgn2q8vpwdm2nzyw79vzlfnai63nf5irr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1-modules" = super.buildPythonPackage rec {
    pname = "pyasn1-modules";
    version = "0.2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl";
      sha256 = "0x0cilayca3lm2wahmxz3z9v7jqnn3v82nfj3mhb6z5rzs7q02x5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl";
      sha256 = "01apwc8fj6qh7lr01yxmns475rfhz07gccr8220ws3wgcwiav0km";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl";
      sha256 = "12y8xwjb118a4jqvvfg9k90kqg03n4d3ygb5csz0l81wxy4pb7gg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.18.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/d7/0fa558c4fb00f15aabc6d42d365fcca7a15fcc1091cd0f5784a14f390b7f/pyrsistent-0.18.0.tar.gz";
      sha256 = "0jzbc3m427wg3r6vxgmcw5517fqpnpakidm7885r1hpq2q97hg3p";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl";
      sha256 = "0answacgnckybm5iyfnaqsgval3mdbpak4i6fsbi2vv8x8qkzfvm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-memcached" = super.buildPythonPackage rec {
    pname = "python-memcached";
    version = "1.59";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/90/19d3908048f70c120ec66a39e61b92c253e834e6e895cd104ce5e46cbe53/python_memcached-1.59-py2.py3-none-any.whl";
      sha256 = "155mk66i3wscb466gmd2h28467lfw4ngq8rk4r83bgbid28n9b2d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-rapidjson" = super.buildPythonPackage rec {
    pname = "python-rapidjson";
    version = "1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/0d/ce00fc9f022f75df39a32890b8a6261204583e1518a8078b99bf66e71578/python-rapidjson-1.4.tar.gz";
      sha256 = "19zgzld46c3idx44lcpychyyyqd89dyl0r7drz4zvk1wk39j1301";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-u2flib-server" = super.buildPythonPackage rec {
    pname = "python-u2flib-server";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/c7/ab44905ecf6300063a4754c9cd3997389fdf5c2c08644ed36c57800c2201/python-u2flib-server-5.0.0.tar.gz";
      sha256 = "09n2phl1qr6rs35kxx02awkwlhdmgd5xnavwl33sn97y2gdl944v";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
  };
  "python-utils" = super.buildPythonPackage rec {
    pname = "python-utils";
    version = "2.5.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/47/974eb168d5012bc8841d4b5be10e345f3e706e25fa1661b68f193e16ca67/python_utils-2.5.6-py2.py3-none-any.whl";
      sha256 = "027jd3qsffdkm363w3lbd16nasx6r3jynj4s0pin344svyhw3yqq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python3-saml" = super.buildPythonPackage rec {
    pname = "python3-saml";
    version = "1.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/08/b61f8513520cbd9d4fca72b58315705ebbb91477fcaca2862cf18431eb5b/python3_saml-1.10.1-py3-none-any.whl";
      sha256 = "1zi3zzlxjshvwv0x38h3k45vl17zsilngl809sp1fq3wza3da12y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."defusedxml"
      self."isodate"
      self."lxml"
      self."xmlsec"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2021.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl";
      sha256 = "0z5qylvysr2zy9n2ylaiwkd0paympz1s3dxa4av5fd25qf5hawin";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rb" = super.buildPythonPackage rec {
    pname = "rb";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/49/efba9585d8cdce5748adc911a7caca2f171b1e47b0204e3d1c5d447aa65e/rb-1.9.0-py2.py3-none-any.whl";
      sha256 = "1ajl65z3ixgsh3ri382apa9szg0sv4p2sjc0yfgiqzmjx9i2qsv0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."redis"
    ];
  };
  "redis" = super.buildPythonPackage rec {
    pname = "redis";
    version = "3.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/05/1fc7feedc19c123e7a95cfc9e7892eb6cdd2e5df4e9e8af6384349c1cc3d/redis-3.4.1-py2.py3-none-any.whl";
      sha256 = "0cq8pf8jjsg4mlb1alj7ziximpzqpznhwkxpim30mzgb0pywy1dj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "redis-py-cluster" = super.buildPythonPackage rec {
    pname = "redis-py-cluster";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/c5/3236720746fa357e214f2b9fe7e517642329f13094fc7eb339abd93d004f/redis_py_cluster-2.1.0-py2.py3-none-any.whl";
      sha256 = "01mbkbkz64liv040bby095z3gpvgdf8r8gjrxa7jfyjw2ifa7ai2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."redis"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl";
      sha256 = "07l7fm7y9zkvmpfli803dni6iwyyhy1f804y46wycam46r70h462";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
  };
  "requests-oauthlib" = super.buildPythonPackage rec {
    pname = "requests-oauthlib";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl";
      sha256 = "0h2iwb3n3d6xplbdnf6sd523kas56y9nygd69ws6pg1v5s7hrvfk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."oauthlib"
      self."requests"
    ];
  };
  "rfc3339-validator" = super.buildPythonPackage rec {
    pname = "rfc3339-validator";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/e7/e18d6cfd3262d48159cd8095eb8f002b5f4e4015e194daffbe0fb706154b/rfc3339_validator-0.1.2-py2.py3-none-any.whl";
      sha256 = "0dfwcm1a40mpcsgfwznw78hc03bjpymvl5vsfjnwxn0bslm6616f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "rfc3986-validator" = super.buildPythonPackage rec {
    pname = "rfc3986-validator";
    version = "0.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/51/17023c0f8f1869d8806b979a2bffa3f861f26a3f1a66b094288323fba52f/rfc3986_validator-0.1.1-py2.py3-none-any.whl";
      sha256 = "1adz53sh2vk34zis232i3fixvnymp4v96dh68c5rfngl5r1mq8rg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rsa" = super.buildPythonPackage rec {
    pname = "rsa";
    version = "4.7.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/93/0c0f002031f18b53af7a6166103c02b9c0667be528944137cc954ec921b3/rsa-4.7.2-py3-none-any.whl";
      sha256 = "1ln9g1ypkymxni43c1r4mrd3qfhy8vkjccsqskgcbq3v9szskybq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "s3transfer" = super.buildPythonPackage rec {
    pname = "s3transfer";
    version = "0.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/89/0cb4e92c239e6425b9b0035227b8cdf9d3d098a5c9e95632c3815df63a09/s3transfer-0.3.7-py2.py3-none-any.whl";
      sha256 = "0iijs1pgp8v30ms4jvbmw280fbfmlgf2hf1qq7asidlpm29bv9gg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."botocore"
    ];
  };
  "selenium" = super.buildPythonPackage rec {
    pname = "selenium";
    version = "3.141.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl";
      sha256 = "0g6bwadmm1757n6yxcd1ihxv04f428kayjmhv6i9jnsspkbk2w9d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."urllib3"
    ];
  };
  "sentry-relay" = super.buildPythonPackage rec {
    pname = "sentry-relay";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/b2/92b7708777cd4130948138f21aa4aa5b12cc82dcd4bfe7d1fc14cfac7bb1/sentry-relay-0.8.8.zip";
      sha256 = "0nr6jh8fkn7by90cnpdk635hy4n7b822x6fx4c34nnc5kylvjl4p";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = with pkgs; [ cargo ];
    checkInputs = [];
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    propagatedBuildInputs = [
      self."milksnake"
    ];
  };
  "sentry-sdk" = super.buildPythonPackage rec {
    pname = "sentry-sdk";
    version = "1.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/5e/72ef257641564379af0ade3cd1ff298a4ca2da24939d4f4aa94f7adb72fe/sentry_sdk-1.4.3-py2.py3-none-any.whl";
      sha256 = "1p56rz1xccpgv9r24z8kysiq2vwrgb6vw3a11qxgw9gz2mqwr4f0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."urllib3"
    ];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "6.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/bf/353180314d0e27929703faf240c244f25ae765e01f595a010cafb209ab51/setuptools_scm-6.3.2-py3-none-any.whl";
      sha256 = "06d1c8qh5h2hc0fzsmnm6cwb3j0iys01dzhbwqx0di293m5l8r2c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
      self."setuptools"
      self."setuptools"
      self."tomli"
      self."tomli"
    ];
  };
  "simplejson" = super.buildPythonPackage rec {
    pname = "simplejson";
    version = "3.17.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/45/a16db4f0fa383aaf0676fb7e3c660304fe390415c243f41a77c7f917d59b/simplejson-3.17.2.tar.gz";
      sha256 = "0hc8nqwdlll4a9cr1k9msn5kmb6kmbjirpgvhjh254nr4sgwgv3m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  six = super.python.pkgs.six;
  #"six" = super.buildPythonPackage rec {
  #  pname = "six";
  #  version = "1.16.0";
  #  src = fetchurl {
  #    url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
  #    sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
  #  };
  #  format = "wheel";
  #  doCheck = false;
  #  buildInputs = [];
  #  checkInputs = [];
  #  nativeBuildInputs = [];
  #  propagatedBuildInputs = [];
  #};
  "snuba-sdk" = super.buildPythonPackage rec {
    pname = "snuba-sdk";
    version = "0.0.25";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/57/2e47eac52aecceec2cc3162e55054e4f4bf0caa7f201e64cc96788521b8b/snuba_sdk-0.0.25-py2.py3-none-any.whl";
      sha256 = "0flhi6x0w8r7imcsbs0zvmmxviri2phss7jznrpgb6qhjzs2xgrn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dataclasses"
    ];
  };
  "soupsieve" = super.buildPythonPackage rec {
    pname = "soupsieve";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/69/d82d04022f02733bf9a72bc3b96332d360c0c5307096d76f6bb7489f7e57/soupsieve-2.2.1-py3-none-any.whl";
      sha256 = "0fy2qjvgwcm4k93lkq133rmwg0sgijpsj93qmgfxp30m9zac5hf2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sqlparse" = super.buildPythonPackage rec {
    pname = "sqlparse";
    version = "0.2.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl";
      sha256 = "1m7y675gs8gwz414xf1xnznrhh2zzgjdyir286h6vcnba47ikkyr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "statsd" = super.buildPythonPackage rec {
    pname = "statsd";
    version = "3.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/33/c824f799128dfcfce2142f18d9bc6c55c46a939f6e4250639134222d99eb/statsd-3.3.0-py2.py3-none-any.whl";
      sha256 = "1ajyacjmq10fd7wq5rggq5ybv121wsy43lk64vv0xjkz6j0gn466";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "structlog" = super.buildPythonPackage rec {
    pname = "structlog";
    version = "21.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/55/ac4c9aa939dc0fce62d5343a77825f4ac9e095b7bb20efc0537c97db1a69/structlog-21.1.0-py2.py3-none-any.whl";
      sha256 = "0iyyh64vm733dfpzksmhxyviw9w7rdkflpkiy208byrjxv06zw32";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "symbolic" = super.buildPythonPackage rec {
    pname = "symbolic";
    version = "8.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/4b/5818d6cdf7b4639e1645899839891ef5951b4c3b50dcef8d515e636ef99e/symbolic-8.3.1.zip";
      sha256 = "0gy1bx6lqadl92r967d2i219r9157qs7kw9083sb1rfqrvbickrj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = with pkgs; [ cargo ];
    checkInputs = [];
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    propagatedBuildInputs = [
      self."milksnake"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/47/f7dab5b63b97efa7a715e389291d46246a5999c7b4705c2d147fc879e3b5/tomli-1.2.1-py3-none-any.whl";
      sha256 = "17w942fmdp3r8rcbc8pxjvyk53kxqpvdnhbbldqn4f3g9m9fkl4d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "toronado" = super.buildPythonPackage rec {
    pname = "toronado";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/4e/0e7515cc7eb30b5caffeb225fe2816bd7d9c207befa621477108938247f3/toronado-0.1.0-py2.py3-none-any.whl";
      sha256 = "0rdvf03rdskaahaa9ccgibrpnbmjdg2zf48p4jy01ijzshppyf4v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cssselect"
      self."cssutils"
      self."lxml"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "3.10.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl";
      sha256 = "0d0s8knd86ldzfygnrj7mwbrhh31rjmksqfhxi3b25p5zpd5xlpi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-inspect" = super.buildPythonPackage rec {
    pname = "typing-inspect";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/fa/77565f652ce57ed56d3a63d537c885a18e4451cf2d56d944991aeb3c82bd/typing_inspect-0.7.1-py3-none-any.whl";
      sha256 = "0sxa7bxah55lx412m0dnd4hbgij4npzyggx322kijxwr7rbd9mrw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mypy-extensions"
      self."typing-extensions"
    ];
  };
  uWSGI = super.pkgs.uwsgi;
  #"uWSGI" = super.buildPythonPackage rec {
  #  pname = "uWSGI";
  #  version = "2.0.19.1";
  #  src = fetchurl {
  #    url = "https://files.pythonhosted.org/packages/c7/75/45234f7b441c59b1eefd31ba3d1041a7e3c89602af24488e2a22e11e7259/uWSGI-2.0.19.1.tar.gz";
  #    sha256 = "0saqkq80mzb0c1kyh0hq408cvlhilp9mh22vb3ay86qb7h2mxa7s";
  #  };
  #  format = "setuptools";
  #  doCheck = false;
  #  buildInputs = [];
  #  checkInputs = [];
  #  nativeBuildInputs = [];
  #  propagatedBuildInputs = [];
  #};
  "ua-parser" = super.buildPythonPackage rec {
    pname = "ua-parser";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/22/4d16b08db329fd440eed366d35e4dd7195c9babb4ecac5218f28081522a2/ua_parser-0.10.0-py2.py3-none-any.whl";
      sha256 = "12kg0fwviyjv7x0pskfsfa7s09jac9yvi4a952mx5nq17hw2xas6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "unidiff" = super.buildPythonPackage rec {
    pname = "unidiff";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/9f/39b58c6c029bedb759d6ba1cf3e8ae56908513c4d4c7f423498724229f2c/unidiff-0.6.0-py2.py3-none-any.whl";
      sha256 = "121sv4hl6clm9vqxi7d92yzf6ycwsbrb4ca9w98l7k1c95m9bpg1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.24.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl";
      sha256 = "1871zqzn8xc33s3fdbzpdbjg1mdx6kpnjn4h31jwfmdv7fi1qaac";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "vine" = super.buildPythonPackage rec {
    pname = "vine";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl";
      sha256 = "1bwq7yx13npsnil8wlljhvvndnfs4pp47mf8jlh6zzfiav64fjga";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "xmlsec" = super.buildPythonPackage rec {
    pname = "xmlsec";
    version = "1.3.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz";
      sha256 = "1ybffmyg2s33c08n600xbd5nwd6vsgkxa36s0i7y1jbhwmnar1ic";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."setuptools-scm"
    ];
    propagatedBuildInputs = [
      self."lxml"
    ];
  };
  "zstandard" = super.buildPythonPackage rec {
    pname = "zstandard";
    version = "0.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/bb/551cd25042138bdd2c36168b837c4ed6196da58fa1cfe3d9de8e70ac23dc/zstandard-0.14.1.tar.gz";
      sha256 = "1ddfipr2kdm64ag6qb9kkbwchdk4dgkws7387za693625vjh1msx";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
