[tool.poetry]
name = "netbox"
version = "2.10.8"
description = ""
authors = ["Your Name <you@example.com>"]
license = "Apache"
packages = [
  { include = "**/*.py", from = "netbox" }
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "3.1.7"
django-cacheops = "5.1"
django-cors-headers = "3.7.0"
django-debug-toolbar = "3.2"
django-filter = "2.4.0"
django-mptt = "0.12.0"
django-pglocks = "1.0.4"
django-prometheus = "2.1.0"
django-rq = "2.4.0"
django-tables2 = "2.3.4"
django-taggit = "1.3.0"
django-timezone-field = "4.1.2"
djangorestframework = "3.12.4"
drf-yasg = {version = "1.20.0", extras = ["validation"]}
gunicorn = "20.0.4"
Jinja2 = "2.11.3"
Markdown = "3.3.4"
netaddr = "0.8.0"
Pillow = "8.1.2"
psycopg2-binary = "2.8.6"
pycryptodome = "3.10.1"
PyYAML = "5.4.1"
svgwrite = "1.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
