name: Build my critical NUR packages and cache it
on:
  push:
    paths:
      - '.github/**'
      - 'pkgs/**'
jobs:
  build-ci-pkgset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: raitobezarius-nur
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: nix-build ./pkgs/ci.nix
